### ISSUE TITLE
目前识别进home assistant的设备无法编辑，只能是只读

### ISSUE THREAD

**Issue by xiemuyun** [skyzhishui/custom_components#2]
不知道这是custom component的特性还是什么原因，lifesmart的设备识别进来之后无法编辑类似entity id、编辑自动化等，在实体注册中显示为只读，看代码中没有 hass.data相关的是不是这个原因？
![image](https://user-images.githubusercontent.com/26018808/76277298-54425700-62c3-11ea-8091-cd4771065f7a.png)

**Comment by skyzhishui** [comment]
嗯，可能是因为我没有开放entity_id的自定义，entity_id现在是根据lifesmart的设备属性拼接成的，修改的话目前会影响基于websocket的状态更新。如果只要修改实体名称和编辑自动化的话，通过customize.yaml和automations.yaml来编辑吧。

**Comment by xiemuyun** [comment]
明白了，使用配置文件还是足够的
